version: '3'

services:
  strapi:
    build: /
    container_name: strapi
    environment:
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
    ports:
      - '1337:1337'
    depends_on:
      - db
    volumes:
      - ./strapi-app:/srv/app

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - ./db-data:/var/lib/mysql

volumes:
  strapi-app:
  db-data:
