version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: charat
      POSTGRES_PASSWORD: Toyota8@
      POSTGRES_DB: testhaha
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
